# Generated by Django 2.1.2 on 2018-10-17 18:06

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('activities', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('hours', models.DecimalField(decimal_places=5, default=0, max_digits=11)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='manager.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timepiece_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'db_table': 'timepiece_entry',
                'ordering': ('-start_time',),
                'permissions': (('can_clock_in', 'Can use Pendulum to clock in'), ('can_clock_out', 'Can use Pendulum to clock out')),
            },
        ),
        migrations.CreateModel(
            name='ProjectHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='start of week')),
                ('hours', models.DecimalField(decimal_places=5, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))])),
                ('published', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project hours entry',
                'verbose_name_plural': 'project hours entries',
                'db_table': 'timepiece_projecthours',
            },
        ),
        migrations.AlterUniqueTogether(
            name='projecthours',
            unique_together={('week_start', 'project', 'user')},
        ),
    ]
