# Generated by Django 2.1.2 on 2018-10-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
