# Generated by Django 2.1.2 on 2018-11-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
