# Generated by Django 2.1.2 on 2018-11-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_todo_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
