# Generated by Django 2.1.2 on 2018-11-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20181106_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['user', 'priority']},
        ),
    ]
