# Generated by Django 2.1.2 on 2018-11-14 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.IntegerField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('char1', models.CharField(blank=True, max_length=100)),
                ('char2', models.CharField(blank=True, max_length=100)),
                ('integer1', models.IntegerField(blank=True)),
                ('integer2', models.IntegerField()),
                ('location', models.ManyToManyField(to='mrp_system.Location')),
                ('manufacturer', models.ManyToManyField(through='mrp_system.ManufacturerRelationship', to='mrp_system.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='partType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='mrp_system.Type'),
        ),
        migrations.AddField(
            model_name='manufacturerrelationship',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Part'),
        ),
    ]
