# Generated by Django 2.1.2 on 2018-11-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0002_auto_20181114_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='fieldType',
            field=models.CharField(choices=[('char1', 'Character 1'), ('char2', 'Character 2'), ('integer1', 'Integer 1'), ('integer2', 'Integer 2')], default='char1', max_length=15),
        ),
    ]
