# Generated by Django 2.1.2 on 2018-11-14 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0004_auto_20181114_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='field',
        ),
        migrations.AddField(
            model_name='field',
            name='typePart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field', to='mrp_system.Type'),
        ),
    ]
