# Generated by Django 2.1.2 on 2018-11-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0005_auto_20181114_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='fields',
            field=models.CharField(choices=[('char1', 'Character 1'), ('char2', 'Character 2'), ('integer1', 'Integer 1'), ('integer2', 'Integer 2')], max_length=15),
        ),
        migrations.AlterField(
            model_name='part',
            name='integer2',
            field=models.IntegerField(blank=True),
        ),
    ]
