# Generated by Django 2.1.2 on 2018-11-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0006_auto_20181114_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='integer1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='integer2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
