# Generated by Django 2.1.2 on 2018-11-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0007_auto_20181114_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Bin',
        ),
    ]
