# Generated by Django 2.1.2 on 2018-11-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0008_auto_20181128_1057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bin',
            new_name='Location',
        ),
    ]
