# Generated by Django 2.1.2 on 2018-12-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0009_auto_20181128_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
