# Generated by Django 2.1.2 on 2018-12-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0013_type_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Location')),
            ],
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='part',
            name='location',
            field=models.ManyToManyField(related_name='loc', to='mrp_system.Location'),
        ),
        migrations.AddField(
            model_name='locationrelationship',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Part'),
        ),
        migrations.AddField(
            model_name='part',
            name='location2',
            field=models.ManyToManyField(through='mrp_system.LocationRelationship', to='mrp_system.Location'),
        ),
    ]
