# Generated by Django 2.1.2 on 2018-12-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0014_auto_20181206_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='location',
        ),
        migrations.AddField(
            model_name='locationrelationship',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerrelationship',
            name='partNumber',
            field=models.IntegerField(blank=True),
        ),
    ]
