# Generated by Django 2.1.2 on 2018-12-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0016_auto_20181206_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='char3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='part',
            name='char4',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='part',
            name='char5',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='part',
            name='char6',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='part',
            name='char7',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='part',
            name='char8',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='part',
            name='char1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='part',
            name='char2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
