# Generated by Django 2.1.2 on 2018-12-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0019_auto_20181206_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='char9',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
