# Generated by Django 2.1.2 on 2018-12-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0020_part_char9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='fields',
            field=models.CharField(choices=[('char1', 'Character 1'), ('char2', 'Character 2'), ('char3', 'Character 3'), ('char4', 'Character 4'), ('char5', 'Character 5'), ('char6', 'Character 6'), ('char7', 'Character 7'), ('char8', 'Character 8'), ('char9', 'Character 9'), ('integer1', 'Integer 1'), ('integer2', 'Integer 2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='partNumber',
            field=models.IntegerField(blank=True, editable=False, max_length=30),
        ),
    ]
