# Generated by Django 2.1.2 on 2018-12-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0021_auto_20181211_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='partNumber',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
