# Generated by Django 2.1.2 on 2018-12-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0022_auto_20181211_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='char10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char11',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char12',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char13',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char14',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char15',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='fields',
            field=models.CharField(choices=[('char1', 'Character 1'), ('char2', 'Character 2'), ('char3', 'Character 3'), ('char4', 'Character 4'), ('char5', 'Character 5'), ('char6', 'Character 6'), ('char7', 'Character 7'), ('char8', 'Character 8'), ('char9', 'Character 9'), ('char10', 'Character 10'), ('char11', 'Character 11'), ('char12', 'Character 12'), ('char13', 'Character 13'), ('char14', 'Character 14'), ('char15', 'Character 15'), ('integer1', 'Integer 1'), ('integer2', 'Integer 2')], max_length=50),
        ),
    ]
