# Generated by Django 2.1.2 on 2018-12-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0023_auto_20181214_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='suffix',
            new_name='prefix',
        ),
        migrations.AddField(
            model_name='part',
            name='char16',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char17',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char18',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char19',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char20',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='fields',
            field=models.CharField(choices=[('char1', 'Character 1'), ('char2', 'Character 2'), ('char3', 'Character 3'), ('char4', 'Character 4'), ('char5', 'Character 5'), ('char6', 'Character 6'), ('char7', 'Character 7'), ('char8', 'Character 8'), ('char9', 'Character 9'), ('char10', 'Character 10'), ('char11', 'Character 11'), ('char12', 'Character 12'), ('char13', 'Character 13'), ('char14', 'Character 14'), ('char15', 'Character 15'), ('char16', 'Character 16'), ('char17', 'Character 17'), ('char18', 'Character 18'), ('char19', 'Character 19'), ('char20', 'Character 20'), ('integer1', 'Integer 1'), ('integer2', 'Integer 2')], max_length=50),
        ),
    ]
