# Generated by Django 2.1.2 on 2018-12-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0026_auto_20181227_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigiKeyAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=150)),
            ],
        ),
    ]
