# Generated by Django 2.1.2 on 2018-12-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0027_digikeyapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigiKeyAPI',
        ),
    ]
