# Generated by Django 2.1.2 on 2018-12-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0031_digikeyapi_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digikeyapi',
            name='date',
        ),
    ]
