# Generated by Django 2.1.2 on 2019-01-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0033_digikeyapi_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='mouser_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
