# Generated by Django 2.1.2 on 2019-01-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0034_field_mouser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerrelationship',
            name='partNumber',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
