# Generated by Django 2.1.2 on 2019-01-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0036_auto_20190111_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
