# Generated by Django 2.1.2 on 2019-01-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0037_billofmaterials_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillofMaterials',
            new_name='Amount',
        ),
    ]
