# Generated by Django 2.1.2 on 2019-01-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0038_auto_20190114_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_products',
            field=models.ManyToManyField(to='mrp_system.Product'),
        ),
    ]
