# Generated by Django 2.1.2 on 2019-01-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0040_auto_20190114_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productamount',
            name='from_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_product', to='mrp_system.Product'),
        ),
        migrations.AlterField(
            model_name='productamount',
            name='to_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_product', to='mrp_system.Product'),
        ),
    ]
