# Generated by Django 2.1.2 on 2019-01-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0041_auto_20190114_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='description',
        ),
    ]
