# Generated by Django 2.1.2 on 2019-01-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0045_auto_20190115_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='component_product',
            field=models.ManyToManyField(through='mrp_system.ProductAmount', to='mrp_system.Product'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='product',
            field=models.ManyToManyField(to='mrp_system.Product'),
        ),
    ]
