# Generated by Django 2.1.2 on 2019-01-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0046_auto_20190115_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
