# Generated by Django 2.1.2 on 2019-01-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0047_billofmaterials_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='BillOfMaterials',
            new_name='ManufacturingOrder',
        ),
        migrations.AddField(
            model_name='moproduct',
            name='manufacturing_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.ManufacturingOrder'),
        ),
        migrations.AddField(
            model_name='moproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Product'),
        ),
    ]
