# Generated by Django 2.1.2 on 2019-01-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0048_auto_20190115_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moproduct',
            name='manufacturing_order',
        ),
        migrations.RemoveField(
            model_name='moproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='MOProduct',
        ),
    ]
