# Generated by Django 2.1.2 on 2019-01-15 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0049_auto_20190115_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.ManufacturingOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Product')),
            ],
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='product',
            field=models.ManyToManyField(through='mrp_system.MOProduct', to='mrp_system.Product'),
        ),
    ]
