# Generated by Django 2.1.2 on 2019-01-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0051_auto_20190118_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerrelationship',
            name='partNumber',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set(),
        ),
    ]
