# Generated by Django 2.1.2 on 2019-01-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0053_auto_20190121_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='name',
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
