# Generated by Django 2.1.2 on 2019-01-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0054_auto_20190121_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
