# Generated by Django 2.1.2 on 2019-01-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0058_product_engimusingproductnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='engimusingProductNumber',
            new_name='engimusing_product_number',
        ),
    ]
