# Generated by Django 2.1.2 on 2019-01-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0060_auto_20190124_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='char22',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char23',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char24',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char25',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char26',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char27',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char28',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char29',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char30',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char31',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char32',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char33',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char34',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='char35',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='fields',
            field=models.CharField(choices=[('char1', 'Character 1'), ('char2', 'Character 2'), ('char3', 'Character 3'), ('char4', 'Character 4'), ('char5', 'Character 5'), ('char6', 'Character 6'), ('char7', 'Character 7'), ('char8', 'Character 8'), ('char9', 'Character 9'), ('char10', 'Character 10'), ('char11', 'Character 11'), ('char12', 'Character 12'), ('char13', 'Character 13'), ('char14', 'Character 14'), ('char15', 'Character 15'), ('char16', 'Character 16'), ('char17', 'Character 17'), ('char18', 'Character 18'), ('char19', 'Character 19'), ('char20', 'Character 20'), ('char21', 'Character 21'), ('char22', 'Character 22'), ('char23', 'Character 23'), ('char24', 'Character 24'), ('char25', 'Character 25'), ('char26', 'Character 26'), ('char27', 'Character 27'), ('char28', 'Character 28'), ('char29', 'Character 29'), ('char30', 'Character 30'), ('char31', 'Character 31'), ('char32', 'Character 32'), ('char33', 'Character 33'), ('char34', 'Character 34'), ('char35', 'Character 35')], max_length=50),
        ),
    ]
