# Generated by Django 2.1.2 on 2019-01-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0063_auto_20190129_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='partNumber',
        ),
    ]
