# Generated by Django 2.1.2 on 2019-01-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0066_auto_20190130_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('manufacturer', 'manufacturer'), ('distributor', 'distrbutor')], default='manufacturer', max_length=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='web_address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
