# Generated by Django 2.1.2 on 2019-01-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0068_auto_20190130_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerrelationship',
            name='manufacturer',
            field=models.ForeignKey(limit_choices_to={'vendor__vendor_type': 'manufacturer'}, on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Vendor'),
        ),
    ]
