# Generated by Django 2.1.2 on 2019-01-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0070_auto_20190130_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
