# Generated by Django 2.1.2 on 2019-01-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0071_auto_20190130_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('manufacturer', 'manufacturer'), ('distributor', 'distributor')], default='manufacturer', max_length=12),
        ),
    ]
