# Generated by Django 2.1.2 on 2019-01-30 16:23

from django.db import migrations, models
import django.db.models.deletion
import mrp_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0072_auto_20190130_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('item_number', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Part')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderparts',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='part',
            field=models.ManyToManyField(through='mrp_system.PurchaseOrderParts', to='mrp_system.Part'),
        ),
    ]
