# Generated by Django 2.1.2 on 2019-01-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0073_auto_20190130_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderparts',
            name='item_number',
            field=models.IntegerField(editable=False),
        ),
    ]
