# Generated by Django 2.1.2 on 2019-01-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0075_auto_20190130_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderparts',
            name='item_number',
        ),
    ]
