# Generated by Django 2.1.2 on 2019-01-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0076_remove_purchaseorderparts_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderparts',
            name='item_number',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
