# Generated by Django 2.1.2 on 2019-01-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0079_vendor_purchase_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='purchase_order',
        ),
    ]
