# Generated by Django 2.1.2 on 2019-01-31 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0080_remove_vendor_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Vendor'),
            preserve_default=False,
        ),
    ]
