from django.urls import path
from django.conf.urls import url

from . import views

urlpatterns = [
    path('', views.TypeListView.as_view(), name='list_types'),
    path('type/create/', views.TypeCreate.as_view(), name='create_type'),
    url(r'^type/edit/(?P<type_id>\d+)/$',
        views.EditType.as_view(),
        name='edit_type'),
    
    url(r'^parts/(?P<type_id>\d+)/$',
        views.ListParts,#.as_view(),
        name='list_parts'),
    url(r'^part/create/(?P<type_id>\d+)/$',
        views.PartCreate,
        name='create_part'),
    url(r'^part/edit/(?P<type_id>\d+)/(?P<id>\d+)$',
        views.PartEdit,
        name='edit_part'),
    url('part/delete/(?P<part_id>\d+)/$',
        views.DeletePart.as_view(),
        name='delete_part'),
    url('part/enter/$',
        views.enter_part,
        name='enter_part'),
    
    path('manufacturer/create/',
         views.CreateManufacturer.as_view(),
         name='create_manufacturer'),
    path('location/create/',
         views.CreateLocation.as_view(),
         name='create_location'),
    path('manufacturer/',
         views.ManufacturerListView.as_view(),
         name='list_manufacturers'),
    path('location/',
         views.LocationListView.as_view(),
         name='list_locations'),
    url('manufacturer/(?P<manufacturer_id>\d+)/$',
        views.ManufacturerUpdate.as_view(),
        name='edit_manufacturer'),
    url('location/(?P<location_id>\d+)/$',
        views.LocationUpdate.as_view(),
        name='edit_location'),
    url('manufacturer/delete/(?P<manufacturer_id>\d+)/$',
        views.ManufacturerDelete.as_view(),
        name='delete_manufacturer'),
    url('location/delete/(?P<location_id>\d+)/$',
        views.LocationDelete.as_view(),
        name='delete_location'),
    url('manufacturer/merge/',
        views.MergeManufacturerView,
        name='merge_manufacturers'),
    url('location/merge/',
        views.MergeLocationView,
        name='merge_locations'),
    url('file/(?P<name>\d+)/$',
        views.view_file,
        name='view_file'),
    url('location/relationship/(?P<locationrelationship_id>\d+)/$',
        views.LocationRelationshipEdit,
        name='edit_loc_rel'),
    url('location/relationship/add/(?P<part_id>\d+)\$',
        views.LocationRelationshipAdd,
        name='add_loc_rel'),
    url('oauth/$',
        views.oauth,
        name='oauth'),
    
]
